(() => {'use strict';
const $=id=>document.getElementById(id);const video=$('camera'),canvas=$('view'),ctx=canvas.getContext('2d',{alpha:false});const work=document.createElement('canvas'),wctx=work.getContext('2d',{willReadFrequently:true});
const DEFAULTS={mode:'green',brightness:1.2,contrast:1.35,gain:1,zoom:.9,fov:35.06,reticle:true,scale:false,measurement:true,vr:false,vrSeparation:.10,vrScale:1,lastDistance:null,measureCalibrationVersion:9,heightAuto:false,cameraHeight:1.65,heightCalibrated:false};let state={...DEFAULTS},raf=0,frames=0,fpsTime=performance.now(),point=null,measureTimer=0,measureStartTimer=0,measureArmedAt=0;
function clamp(v,a,b){return Math.min(b,Math.max(a,v))}function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}const KEY='lonewolf-nightvision-v9';
function refreshRealFov(){if(!LW.camera?.fovHorizontal)return;LW.measure.configureCamera(LW.camera.getFovInfo());state.fov=LW.measure.verticalFov(canvas.width,canvas.height,state.zoom)}
function load(){try{const v=localStorage.getItem(KEY);if(v)state={...DEFAULTS,...JSON.parse(v)}}catch(e){}state.heightAuto=!!state.heightAuto;state.cameraHeight=clamp(Number(state.cameraHeight)||1.65,.70,1.65);if(state.heightAuto){LW.measure.setCameraHeight(state.cameraHeight)}else LW.measure.clearAutoHeight();if(state.measureCalibrationVersion!==9){state.fov=35.06;state.measureCalibrationVersion=9}state.brightness=clamp(+state.brightness,.6,2);state.contrast=clamp(+state.contrast,.6,2.5);state.gain=clamp(+state.gain,.5,3);state.zoom=clamp(+state.zoom,.9,4);state.fov=clamp(+state.fov,25,50);state.vrSeparation=clamp(+state.vrSeparation,0,.2);state.vrScale=clamp(+state.vrScale,.85,1.15);state.measureActive=false;state.measureArmed=false;state.measureConfirmed=false;state.measureProgress=0;sync()}
function sync(){document.body.dataset.mode=state.mode;$('brightness').value=state.brightness;$('contrast').value=state.contrast;$('gain').value=state.gain;$('zoom').value=state.zoom;$('fov').value=state.fov;$('brightnessOut').textContent=state.brightness.toFixed(2);$('contrastOut').textContent=state.contrast.toFixed(2);$('gainOut').textContent=state.gain.toFixed(2);$('zoomOut').textContent=state.zoom.toFixed(1)+'×';$('fovOut').textContent=state.fov.toFixed(1)+'° REAL';$('vrSeparationOut').textContent=Math.round(state.vrSeparation*100)+'%';$('vrScaleOut').textContent=state.vrScale.toFixed(2)+'×';$('modeLabel').textContent={green:'VERDE NV',bw:'BLANCO / NEGRO',thermal:'TÉRMICO',normal:'NORMAL'}[state.mode];document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));$('reticleToggle').textContent=state.reticle?'RETÍCULA ON':'RETÍCULA OFF';$('reticleToggle').classList.toggle('active',state.reticle);$('measureToggle').textContent=state.measurement?'MEDICIÓN ON':'MEDICIÓN OFF';$('measureToggle').classList.toggle('active',state.measurement);$('vrToggle').textContent=state.vr?'VR BOX ON':'VR BOX OFF';$('vrToggle').classList.toggle('active',state.vr);const hs=$('heightStatus');if(hs)hs.textContent=state.heightAuto?'AUTO '+state.cameraHeight.toFixed(2)+' M':'BASE 1.65 M';if(state.measureArmed&&!state.measureConfirmed)$('hint').textContent='MODO MEDICIÓN ACTIVADO · FIJE RETÍCULA AL OBJETO POR 1 SEGUNDO';else if(state.measureConfirmed)$('hint').textContent='MEDICIÓN COMPLETADA';else $('hint').textContent='SACUDIDA ≥ 1° PARA MEDIR';LW.vr.setHUD(state.vr);updateVRHudText()}
function updateVRHudText(){document.querySelectorAll('.vr-hud').forEach(hud=>{hud.innerHTML=`<div class="topbar"><span>${$('modeLabel').textContent}</span><span>${$('cameraLabel').textContent}</span><span>${$('fps').textContent}</span></div><div class="compass-hud"><div class="compass-window"><div class="compass-ticks"></div><div class="compass-center"></div></div><div class="compass-readout">${$('compassReadout').textContent}</div></div><div class="distance">${$('distanceHud').textContent}</div><div class="hint">${$('hint').textContent}</div>`});if(LW.compass?.syncVR)LW.compass.syncVR()}
function isLandscape(){const mq=window.matchMedia?.('(orientation: landscape)');if(mq)return mq.matches;const a=Number(screen.orientation?.angle);if(a===90||a===270)return true;return innerWidth>innerHeight}
function updateOrientationGuard(){const portrait=!isLandscape();$('orientationGuard').classList.toggle('hidden',!portrait);$('menuBtn').classList.toggle('hidden',portrait);$('compassHUD').classList.toggle('hidden',portrait||state.vr);$('distanceHud').classList.toggle('hidden',portrait||state.vr);$('hint').classList.toggle('hidden',portrait||state.vr);return !portrait}
function resize(){const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);const pw=Math.min(960,Math.max(640,Math.round(innerWidth*dpr))),vw=video.videoWidth||1920,vh=video.videoHeight||1080;work.width=pw;work.height=Math.max(360,Math.round(pw/(vw/vh)));if(LW.camera?.fovHorizontal){LW.measure.configureCamera(LW.camera.getFovInfo());state.fov=LW.measure.verticalFov(canvas.width,canvas.height,state.zoom)}updateOrientationGuard();sync()}
async function start(){ $('bootMessage').textContent='';try{if(!isLandscape()){updateOrientationGuard();$('bootMessage').textContent='GIRA EL DISPOSITIVO HORIZONTALMENTE PARA INICIAR.';return}const sensors=await LW.measureGesture.requestPermission();if(!sensors)console.warn('Sensores no autorizados.');await LW.compass.start();await LW.camera.start();$('boot').classList.add('hidden');$('cameraLabel').textContent='CAM TRASERA · PAISAJE';resize();refreshRealFov();LW.measureGesture.start(()=>{if(state.measurement&&!state.measureActive&&!state.measureArmed)beginMeasurement()});sync();render()}catch(e){let m='No se pudo iniciar la cámara.';if(e.name==='NotAllowedError')m='Permiso de cámara/orientación/movimiento bloqueado. Habilitalo para este sitio.';if(e.name==='NotReadableError')m='La cámara está ocupada o Safari no pudo acceder a ella.';$('bootMessage').textContent=m;console.error(e)}}
function beginMeasurement(){if(!state.measurement||state.measureActive||state.measureArmed)return;state.measureArmed=true;state.measureConfirmed=false;state.measureProgress=0;measureArmedAt=performance.now();point={x:canvas.width/2,y:canvas.height/2};sync();save();clearTimeout(measureStartTimer);clearTimeout(measureTimer);measureStartTimer=setTimeout(()=>captureMeasurement(),1000)}
function captureMeasurement(){if(!state.measureArmed||state.measureConfirmed)return;state.measureProgress=1;const pitch=LW.measureGesture.pitchDegrees();if(state.heightCalibrationArmed){const h=LW.measure.heightFromKnownReference(20,Number(pitch)*Math.PI/180);if(h){state.cameraHeight=h;state.heightAuto=true;state.heightCalibrated=true;state.heightCalibrationArmed=false;setDistance({value:h,text:'ALTURA '+h.toFixed(2)+' M'});state.measureActive=true;state.measureConfirmed=true;sync();save();clearTimeout(measureTimer);measureTimer=setTimeout(()=>endMeasurement(),3000);return}state.heightCalibrationArmed=false;state.measureConfirmed=false;state.measureArmed=false;state.measureProgress=0;point=null;sync();save();return}setDistance(LW.measure.distanceFromPitchDegrees(pitch));state.measureActive=true;state.measureConfirmed=true;sync();save();clearTimeout(measureTimer);measureTimer=setTimeout(()=>endMeasurement(),3000)}
function endMeasurement(){clearTimeout(measureStartTimer);clearTimeout(measureTimer);measureStartTimer=0;measureTimer=0;measureArmedAt=0;if(!state.measureActive&&!state.measureArmed)return;state.measureActive=false;state.measureArmed=false;state.measureConfirmed=false;state.measureProgress=0;point=null;setDistance(null);sync();save()}
function updateMeasurement(){if(!state.measureArmed||state.measureConfirmed)return;state.measureProgress=Math.min(1,(performance.now()-measureArmedAt)/1000)}
function toggleVR(){state.vr=!state.vr;if(!state.vr&&(state.measureActive||state.measureArmed))endMeasurement();sync();save();updateOrientationGuard()}
function render(){if(LW.camera.running)drawFrame();updateMeasurement();drawOverlay();frames++;const n=performance.now();if(n-fpsTime>1000){$('fps').textContent=frames+' FPS';frames=0;fpsTime=n;updateVRHudText()}raf=requestAnimationFrame(render)}
function drawFrame(){const vw=video.videoWidth,vh=video.videoHeight,cw=canvas.width,ch=canvas.height,asp=cw/ch,src=vw/vh,z=state.zoom;let sw,sh;if(src>asp){sh=vh/z;sw=sh*asp}else{sw=vw/z;sh=sw/asp}sw=Math.min(sw,vw);sh=Math.min(sh,vh);const sx=(vw-sw)/2,sy=(vh-sh)/2;work.height=Math.max(360,Math.round(work.width/(sw/sh)));wctx.drawImage(video,sx,sy,sw,sh,0,0,work.width,work.height);const img=wctx.getImageData(0,0,work.width,work.height);LW.image.process(img.data,state);wctx.putImageData(img,0,0);ctx.clearRect(0,0,cw,ch);if(state.vr)LW.vr.draw(ctx,work,cw,ch,state);else ctx.drawImage(work,0,0,cw,ch)}
function drawOverlay(){let extra={...state,point,measureActive:state.measureActive||state.measureArmed,measureProgress:state.measureProgress,measureConfirmed:state.measureConfirmed};if(state.vr)LW.vr.drawOverlay(ctx,canvas.width,canvas.height,extra,null);else LW.reticle.draw(ctx,canvas.width,canvas.height,extra)}
function setDistance(res){const text=res?res.text:'--';$('distanceHud').textContent='DIST: '+text;$('distanceValue').textContent=text;state.lastDistance=res?.value??null;updateVRHudText()}
function bind(){
$('startBtn').onclick=start;$('menuBtn').onclick=()=>$('controls').classList.toggle('hidden');$('closeBtn').onclick=()=>$('controls').classList.add('hidden');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;sync();save()});[['brightness','brightness'],['contrast','contrast'],['gain','gain'],['zoom','zoom'],['vrSeparation','vrSeparation'],['vrScale','vrScale']].forEach(([id,key])=>$(id).oninput=e=>{state[key]=+e.target.value;if(key==='zoom'&&LW.camera.running)state.fov=LW.measure.verticalFov(canvas.width,canvas.height,state.zoom);sync();save()});$('reticleToggle').onclick=()=>{state.reticle=!state.reticle;sync();save()};$('measureToggle').onclick=()=>{state.measurement=!state.measurement;if(!state.measurement)endMeasurement();sync();save()};$('vrToggle').onclick=toggleVR;
const hb=$('heightCalibrateBtn');if(hb)hb.onclick=()=>{state.heightCalibrationArmed=true;state.measurement=true;state.measureActive=false;state.measureArmed=false;state.measureConfirmed=false;state.measureProgress=0;$('hint').textContent='AUTO HEIGHT · APUNTE A LA BASE DE LA REFERENCIA DE 20 M Y SACUDA ≥ 1°';sync();save()};
$('resetBtn').onclick=()=>{endMeasurement();state={...DEFAULTS,measureActive:false,measureArmed:false,measureConfirmed:false,measureProgress:0};LW.measure.clearAutoHeight();if(LW.camera.running)refreshRealFov();else LW.measure.fov=state.fov;sync();save();setDistance(null)}}
document.addEventListener('DOMContentLoaded',()=>{try{load();bind();resize();addEventListener('resize',resize);addEventListener('orientationchange',()=>setTimeout(resize,250));screen.orientation?.addEventListener?.('change',()=>setTimeout(resize,100));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(reg=>{reg.update().catch(()=>{});if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'})}).catch(console.warn)}catch(e){console.error('Lonewolf startup:',e);const boot=document.getElementById('boot'),msg=document.getElementById('bootMessage');if(boot)boot.classList.remove('hidden');if(msg)msg.textContent='No se pudo iniciar la aplicación. Recargá esta Web App.'}});window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);LW.measureGesture?.stop();LW.compass?.stop();LW.camera.stop()});})();
