(()=>{'use strict';
const $=id=>document.getElementById(id),video=$('camera'),canvas=$('view'),ctx=canvas.getContext('2d',{alpha:false}),work=document.createElement('canvas'),wctx=work.getContext('2d',{willReadFrequently:true});
const DEFAULTS={mode:'green',brightness:1.2,contrast:1.35,gain:1,zoom:.9,fov:35.06,reticle:true,scale:false,measurement:true,vr:false,vrSeparation:.10,vrScale:1,lastDistance:null,measureCalibrationVersion:20,heightAuto:false,cameraHeight:1.65,heightCalibrated:false};
let state={...DEFAULTS},raf=0,frames=0,fpsTime=performance.now(),measureStartTimer=0,pointTimer=0,resultTimer=0,cooldownTimer=0,measureArmedAt=0,pointStage='',basePoint=null,topPoint=null,baseY=null,topY=null;
const KEY='lonewolf-nightvision-v20';
function clamp(v,a,b){return Math.min(b,Math.max(a,v))}function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function refreshRealFov(){if(!LW.camera?.fovHorizontal)return;LW.measure.configureCamera(LW.camera.getFovInfo());state.fov=LW.measure.verticalFov(canvas.width,canvas.height,.9)}
function load(){try{const v=localStorage.getItem(KEY);if(v)state={...DEFAULTS,...JSON.parse(v)}}catch(e){}state.cameraHeight=clamp(Number(state.cameraHeight)||1.65,.70,1.65);state.brightness=clamp(+state.brightness,.6,2);state.contrast=clamp(+state.contrast,.6,2.5);state.gain=clamp(+state.gain,.5,3);state.zoom=.9;state.fov=clamp(+state.fov,25,50);state.vrSeparation=clamp(+state.vrSeparation,0,.2);state.vrScale=clamp(+state.vrScale,.85,1.15);clearMeasurementState();sync()}
function clearMeasurementState(){state.measureActive=false;state.measureArmed=false;state.measureConfirmed=false;state.measureProgress=0;state.measureStage='';state.measureCooldown=false;state.measureMessage='';basePoint=topPoint=null;baseY=topY=null;pointStage='';}
function normalHUDVisible(){return !state.vr&&!$('orientationGuard')?.classList.contains('hidden')===false}
function sync(){state.zoom=.9;document.body.dataset.mode=state.mode;[['brightness',state.brightness],['contrast',state.contrast],['zoom',.9],['fov',state.fov]].forEach(([id,v])=>{const e=$(id);if(e){e.value=v;e.disabled=id==='zoom';if(id==='zoom')e.setAttribute('aria-disabled','true')}});[['brightnessOut',state.brightness.toFixed(2)],['contrastOut',state.contrast.toFixed(2)],['gainOut',state.gain.toFixed(2)],['zoomOut','0.9× FIJO'],['fovOut',state.fov.toFixed(1)+'° REAL'],['vrSeparationOut',Math.round(state.vrSeparation*100)+'%'],['vrScaleOut',state.vrScale.toFixed(2)+'×']].forEach(([id,v])=>{const e=$(id);if(e)e.textContent=v});const m=$('modeLabel');if(m)m.textContent={green:'VERDE NV',bw:'BLANCO / NEGRO',thermal:'TÉRMICO',normal:'NORMAL'}[state.mode];document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));const rt=$('reticleToggle');if(rt){rt.textContent=state.reticle?'RETÍCULA ON':'RETÍCULA OFF';rt.classList.toggle('active',state.reticle)}const mt=$('measureToggle');if(mt){mt.textContent=state.measurement?'MEDICIÓN ON':'MEDICIÓN OFF';mt.classList.toggle('active',state.measurement)}const vt=$('vrToggle');if(vt){vt.textContent=state.vr?'VR BOX ON':'VR BOX OFF';vt.classList.toggle('active',state.vr)}const hs=$('heightStatus');if(hs)hs.textContent=state.heightAuto?'AUTO '+state.cameraHeight.toFixed(2)+' M':'BASE 1.65 M';const h=$('hint');if(h)h.textContent=getMeasurementMessage();if(LW.vr)LW.vr.setHUD(state.vr);updateHUDVisibility();updateVRHudText()}
function getMeasurementMessage(){if(state.measureCooldown)return'MEDICIÓN BLOQUEADA · ESPERE 5 SEGUNDOS';if(state.measureStage==='waiting')return'INICIO MODO MEDICIÓN';if(state.measureStage==='base')return'FIJE EL PUNTO EN LA BASE DEL OBJETO';if(state.measureStage==='baseLocked')return'BASE FIJADA ✓ · APUNTE A LA PARTE SUPERIOR';if(state.measureStage==='top')return'FIJE EL PUNTO EN LA PARTE SUPERIOR';if(state.measureStage==='topLocked')return'ALTURA FIJADA ✓ · CALCULANDO';if(state.measureStage==='result')return state.lastDistance?'DISTANCIA '+state.lastDistance:'FUERA DE RANGO';return'GIRE IZQUIERDA/DERECHA ≥ 45° PARA MEDIR'}
function updateHUDVisibility(){const portrait=!isLandscape();$('orientationGuard')?.classList.toggle('hidden',!portrait);$('menuBtn')?.classList.toggle('hidden',portrait);$('compassHUD')?.classList.toggle('hidden',portrait||state.vr);$('distanceHud')?.classList.toggle('hidden',portrait||state.vr);$('hint')?.classList.toggle('hidden',portrait||state.vr);document.querySelectorAll('.vr-hud').forEach(el=>el.classList.toggle('active',state.vr&&!portrait))}
function updateVRHudText(){document.querySelectorAll('.vr-hud').forEach(h=>{h.innerHTML=`<div class="topbar vr-large"><span>${$('modeLabel')?.textContent||''}</span><span>${$('cameraLabel')?.textContent||''}</span><span>${$('fps')?.textContent||''}</span></div><div class="compass-hud"><div class="compass-window"><div class="compass-ticks"></div><div class="compass-center"></div></div><div class="compass-readout vr-large">${$('compassReadout')?.textContent||'N 000°'}</div></div><div class="distance vr-large">${state.lastDistance?'DISTANCIA: '+state.lastDistance:'DISTANCIA: --'}</div><div class="hint vr-large">${getMeasurementMessage()}</div>`});if(LW.compass?.syncVR)LW.compass.syncVR()}
function isLandscape(){const mq=window.matchMedia?.('(orientation: landscape)');if(mq)return mq.matches;const a=Number(screen.orientation?.angle);return a===90||a===270||innerWidth>innerHeight}
function resize(){const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);const pw=Math.min(960,Math.max(640,Math.round(innerWidth*dpr))),vw=video.videoWidth||1920,vh=video.videoHeight||1080;work.width=pw;work.height=Math.max(360,Math.round(pw/(vw/vh)));if(LW.camera?.fovHorizontal){LW.measure.configureCamera(LW.camera.getFovInfo());state.fov=LW.measure.verticalFov(canvas.width,canvas.height,.9)}updateHUDVisibility();sync()}
async function start(){const bm=$('bootMessage');if(bm)bm.textContent='';try{if(!isLandscape()){updateHUDVisibility();if(bm)bm.textContent='GIRA EL DISPOSITIVO HORIZONTALMENTE PARA INICIAR.';return}await LW.camera.start();$('boot')?.classList.add('hidden');if($('cameraLabel'))$('cameraLabel').textContent='CAM TRASERA · PAISAJE';resize();refreshRealFov();try{await LW.measureGesture.requestPermission()}catch(e){console.warn('Sensor permission unavailable',e)}try{await LW.compass.start()}catch(e){console.warn('Compass unavailable',e)}LW.measureGesture.start(()=>{if(state.measurement&&!state.measureActive&&!state.measureArmed&&!state.measureCooldown)beginMeasurement()});sync();render()}catch(e){let m='No se pudo iniciar la cámara.';if(e.name==='NotAllowedError'||e.name==='SecurityError')m='Permiso de cámara bloqueado. Habilítalo para este sitio.';if(e.name==='NotReadableError')m='La cámara está ocupada o Safari no pudo acceder a ella.';if(bm)bm.textContent=m;console.error('Camera start:',e)}}
function beginMeasurement(){if(!state.measurement||state.measureActive||state.measureArmed||state.measureCooldown)return;state.measureArmed=true;state.measureStage='waiting';state.measureProgress=0;state.lastDistance=null;measureArmedAt=performance.now();basePoint=topPoint=null;baseY=topY=null;sync();save();clearTimeout(measureStartTimer);measureStartTimer=setTimeout(startBaseStage,2000)}
function startBaseStage(){if(!state.measureArmed)return;state.measureStage='base';state.measureProgress=0;pointStage='base';measureArmedAt=performance.now();sync();clearTimeout(pointTimer);pointTimer=setTimeout(lockBasePoint,1000)}
function lockBasePoint(){if(!state.measureArmed||state.measureStage!=='base')return;baseY=canvas.height/2;/* The reticle is centered; the user fixes the base before this timer expires. */basePoint={x:canvas.width/2,y:baseY};state.measureStage='baseLocked';state.measureProgress=0;sync();pointStage='top';setTimeout(()=>{if(state.measureArmed&&state.measureStage==='baseLocked'){state.measureStage='top';measureArmedAt=performance.now();sync();clearTimeout(pointTimer);pointTimer=setTimeout(lockTopPoint,1000)}},350)}
function lockTopPoint(){if(!state.measureArmed||state.measureStage!=='top')return;topY=canvas.height/2;topPoint={x:canvas.width/2,y:topY};state.measureStage='topLocked';sync();clearTimeout(pointTimer);setTimeout(calculateTwoPointMeasurement,250)}
function calculateTwoPointMeasurement(){if(!state.measureArmed)return;const result=LW.measure.distanceFromTwoScreenPoints(baseY,topY,canvas.height,canvas.width,.9);setDistance(result);state.measureStage='result';state.measureActive=true;state.measureConfirmed=true;state.measureArmed=false;sync();save();clearTimeout(resultTimer);resultTimer=setTimeout(endMeasurement,3000)}
function endMeasurement(){clearTimeout(measureStartTimer);clearTimeout(pointTimer);clearTimeout(resultTimer);measureStartTimer=pointTimer=resultTimer=0;state.measureActive=false;state.measureArmed=false;state.measureConfirmed=false;state.measureProgress=0;state.measureStage='';basePoint=topPoint=null;baseY=topY=null;setDistance(null);state.measureCooldown=true;sync();save();clearTimeout(cooldownTimer);cooldownTimer=setTimeout(()=>{state.measureCooldown=false;sync();save()},5000)}
function updateMeasurement(){if(state.measureStage==='waiting'||state.measureStage==='base'||state.measureStage==='top')state.measureProgress=Math.min(1,(performance.now()-measureArmedAt)/1000)}
function toggleVR(){state.vr=!state.vr;if(!state.vr&&state.measureActive)endMeasurement();sync();save();updateHUDVisibility()}
function render(){if(LW.camera.running)drawFrame();updateMeasurement();drawOverlay();frames++;const n=performance.now();if(n-fpsTime>1000){if($('fps'))$('fps').textContent=frames+' FPS';frames=0;fpsTime=n;updateVRHudText()}raf=requestAnimationFrame(render)}
function drawFrame(){const vw=video.videoWidth,vh=video.videoHeight,cw=canvas.width,ch=canvas.height,asp=cw/ch,src=vw/vh,z=.9;let sw,sh;if(src>asp){sh=vh/z;sw=sh*asp}else{sw=vw/z;sh=sw/asp}sw=Math.min(sw,vw);sh=Math.min(sh,vh);const sx=(vw-sw)/2,sy=(vh-sh)/2;work.height=Math.max(360,Math.round(work.width/(sw/sh)));wctx.drawImage(video,sx,sy,sw,sh,0,0,work.width,work.height);const img=wctx.getImageData(0,0,work.width,work.height);LW.image.process(img.data,state);wctx.putImageData(img,0,0);ctx.clearRect(0,0,cw,ch);if(state.vr)LW.vr.draw(ctx,work,cw,ch,state);else ctx.drawImage(work,0,0,cw,ch)}
function drawOverlay(){const extra={...state,zoom:.9,measureActive:state.measureActive||state.measureArmed,measureProgress:state.measureProgress,measureConfirmed:state.measureConfirmed,measureStage:state.measureStage,basePoint,topPoint};if(state.vr)LW.vr.drawOverlay(ctx,canvas.width,canvas.height,extra,null);else LW.reticle.draw(ctx,canvas.width,canvas.height,extra)}
function setDistance(res){const text=res?res.text:'--';if($('distanceHud'))$('distanceHud').textContent='DIST: '+text;if($('distanceValue'))$('distanceValue').textContent=text;state.lastDistance=res?.value?res.value.toFixed(1)+' M':null;updateVRHudText()}
function bind(){const sb=$('startBtn');if(!sb)return;sb.onclick=start;if($('menuBtn'))$('menuBtn').onclick=()=>$('controls').classList.toggle('hidden');if($('closeBtn'))$('closeBtn').onclick=()=>$('controls').classList.add('hidden');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;sync();save()});[['brightness','brightness'],['contrast','contrast'],['zoom','zoom'],['vrSeparation','vrSeparation'],['vrScale','vrScale']].forEach(([id,key])=>{const e=$(id);if(e)e.oninput=x=>{if(key==='zoom'){state.zoom=.9;sync();return}state[key]=+x.target.value;sync();save()}});if($('reticleToggle'))$('reticleToggle').onclick=()=>{state.reticle=!state.reticle;sync();save()};if($('measureToggle'))$('measureToggle').onclick=()=>{state.measurement=!state.measurement;if(!state.measurement)endMeasurement();sync();save()};if($('vrToggle'))$('vrToggle').onclick=toggleVR;if($('resetBtn'))$('resetBtn').onclick=()=>{endMeasurement();state={...DEFAULTS};LW.measure.clearAutoHeight();sync();save()}}
document.addEventListener('DOMContentLoaded',()=>{try{load();bind();resize();addEventListener('resize',resize);addEventListener('orientationchange',()=>setTimeout(resize,250));screen.orientation?.addEventListener?.('change',()=>setTimeout(resize,100));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(reg=>{reg.update().catch(()=>{});if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'})}).catch(console.warn)}catch(e){console.error('Lonewolf startup:',e);$('boot')?.classList.remove('hidden');if($('bootMessage'))$('bootMessage').textContent='No se pudo iniciar la aplicación. Recargá esta Web App.'}});window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);LW.measureGesture?.stop();LW.compass?.stop();LW.camera.stop()});
})();
