window.LW=window.LW||{};
LW.compass=(()=>{const HUD_ID='compassHUD',TICKS_ID='compassTicks',READOUT_ID='compassReadout',PX_PER_DEG=4.2;let heading=null,listening=false;
const normalize=d=>((d%360)+360)%360;const label=d=>{const n=normalize(d);if(n===0)return'N';if(n===90)return'E';if(n===180)return'S';if(n===270)return'O';if(n===45)return'NE';if(n===135)return'SE';if(n===225)return'SO';if(n===315)return'NO';return''};
function buildTicks(el){if(!el||el.childElementCount)return;for(let d=-1080;d<=1080;d+=5){const tick=document.createElement('div'),a=normalize(d);tick.className='compass-tick'+(a%10===0?' major':'')+(a%45===0?' cardinal':'');tick.style.left=d*PX_PER_DEG+'px';if(a%45===0){const s=document.createElement('span');s.textContent=label(a)||String(a).padStart(3,'0')+'°';tick.appendChild(s)}else if(a%30===0){const s=document.createElement('span');s.textContent=String(a).padStart(3,'0')+'°';tick.appendChild(s)}el.appendChild(tick)}}
function renderOne(h,root){const el=root.querySelector('.compass-ticks');buildTicks(el);if(el)el.style.transform=`translateX(${-h*PX_PER_DEG}px)`;const r=root.querySelector('.compass-readout');if(r){const deg=Math.round(h)%360;r.textContent=`${label(deg)||''} ${String(deg).padStart(3,'0')}°`.trim()}}
function render(h){const root=document.getElementById(HUD_ID);if(root)renderOne(h,root);document.querySelectorAll('.vr-hud').forEach(renderOne.bind(null,h))}
function handle(e){let h=null;if(typeof e.webkitCompassHeading==='number'&&isFinite(e.webkitCompassHeading))h=normalize(e.webkitCompassHeading);else if(e.absolute&&typeof e.alpha==='number'&&isFinite(e.alpha))h=normalize(360-e.alpha);if(h===null)return;heading=h;render(h)}
async function start(){buildTicks(document.getElementById(TICKS_ID));if(listening)return true;try{if(typeof DeviceOrientationEvent==='undefined'){document.getElementById(READOUT_ID).textContent='BRÚJULA: NO DISP.';return false}if(typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission(true);if(p!=='granted'){document.getElementById(READOUT_ID).textContent='BRÚJULA: SIN PERMISO';return false}}window.addEventListener('deviceorientationabsolute',handle,true);window.addEventListener('deviceorientation',handle,true);listening=true;return true}catch(err){console.warn('Compass permission:',err);document.getElementById(READOUT_ID).textContent='BRÚJULA: SIN SEÑAL';return false}}
function stop(){if(!listening)return;window.removeEventListener('deviceorientationabsolute',handle,true);window.removeEventListener('deviceorientation',handle,true);listening=false}
function syncVR(){if(heading!==null)document.querySelectorAll('.vr-hud').forEach(root=>renderOne(heading,root))}
return{start,stop,syncVR,get heading(){return heading}}})()
